// Generated by CoffeeScript 2.3.1
(function() {
  var edge;

  edge = require('edge-js');

  
  var method = edge.func({
      assemblyFile : '../../ConsoleApp2/ConsoleApp2/bin/Debug/Adodb.dll' ,
      // typeNme : 'Adodb.Ado;db',
      methodName : 'Inserts'
  });

  var payload = {
      table : 'Bookings',
      table_id : '34' ,
      primary_key : 'ref'
  }
  //`
  //    func = edge.func( 'sql' , function() { /*
  //      select * from bookings;
  //*/
  //    })
  //`
;

  method(payload, function(err, data) {
    var i, len, rec, results;
    if (err) {
      return console.error(err);
    } else {
      results = [];
      for (i = 0, len = data.length; i < len; i++) {
        rec = data[i];
        results.push(console.log(rec));
      }
      return results;
    }
  });

}).call(this);

//# sourceMappingURL=edge.js.map
