// Generated by CoffeeScript 2.3.1
(function() {
  var Controller, Db, TC, locomotive,
    boundMethodCheck = function(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new Error('Bound instance method accessed before binding'); } };

  locomotive = require('locomotive');

  Controller = locomotive.Controller;

  Db = require('../db');

  TC = class TC extends Controller {
    constructor() {
      super();
      this.show = this.show.bind(this);
      this.primary = new Db("primary", "E:\\ResMgr\\amdex\\resmanager", "AERLINGUS");
      this.snapshot = new Db("snapshot", "E:\\ResMgr\\amdex\\resmanager_snapshot");
    }

    index() {
      return this.primary.getTables(this.show);
    }

    show() {
      boundMethodCheck(this, TC);
      this.title = "Hello World";
      this.tables = this.primary.tables; // locomotive filters all properties existing prior to action !!
      return this.render();
    }

  };

  module.exports = TC;

}).call(this);

//# sourceMappingURL=tablesController.js.map
